name: "Build image"

on:
  pull_request_target:
    # The branches below must be a subset of the branches above
    branches: [ "current" ]

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  build-image:
    uses: vyos/.github/.github/workflows/build-image.yml@feature/T6732-image-build-workflow
    secrets: inherit
    with:
      debian_mirror_url: 'http://deb.debian.org/debian/'
      debian_security_mirror_url: ''
      vyos_mirror_base_url: 'https://packages.vyos.net/repositories'
      arch: 'amd64'
      build_by: 'autobuild@vyos.net'
      release_version: '1.5.1'
      release_flavor: 'generic'
