name: "Build image"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "current" ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql-analysis-call:
    uses: vyos/.github/.github/workflows/build-image.yml@feature/T6732-image-build-workflow
    secrets: inherit
    with:
      release_version: "1.5"