---
name: Darker-Ruff Lint

on:
  pull_request_target:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read
  
env:
  base_ref: ${{ github.event.pull_request.base.ref }}

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          # ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-python@v5

      - name: darker install
        run: |
          pip install git+https://github.com/akaihola/darker.git@master ruff>=0.0.292

      # - name: Fetch base branch
      #   run: |
      #     git fetch origin ${base_ref}:refs/remotes/origin/base-current

      - name: Fetch base and head commits
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}:refs/remotes/origin/base
          git fetch origin ${{ github.event.pull_request.head.sha }}:refs/remotes/origin/head
          git branch temp-base refs/remotes/origin/temp-base
          git branch temp-head refs/remotes/origin/temp-head

      - name: Analyze Code
        run: |
          darker -r temp-base...temp-head --check --diff --lint "ruff check" --color .