---
name: Darker-Ruff Lint

on:
  pull_request:
    branches:
      - current

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-python@v5

      - name: darker install
        run: |
          pip install git+https://github.com/akaihola/darker.git@master isort==5.11.4 ruff>=0.0.292

      - name: Fetch base branch
        run: |
          git fetch origin ref: ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Analyze Code with Darker
        run: |
          darker -r current... --check --diff --lint "ruff check" --isort --color ./src
