---
name: Ruff Lint

on: [push, pull_request]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: chartboost/ruff-action@491342200cdd1cf4d5132a30ddc546b3b5bc531b
        with:
          changed-files: 'true'
