name: VyOS var pass test

on:
  workflow_dispatch:

jobs:
  call_var_pass:
    uses: vyos/.github/.github/workflows/var-pass.yml@feature/test-var-passing
    with:
      NETLIFY_SITE_NAME: ${{ vars.NETLIFY_SITE_NAME }}  
